[package]
name = "lattice_solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion = "0.5.1"
fixedbitset = "0.4.2"
itertools = "0.12.1"
json = "0.12.4"
kdam = {version="0.5.1", features = ["template", "spinner", "gradient"]}
kiddo = "4.0.0"

[[bench]]
name = "benchmarks"
harness = false

[[bench]]
name = "full_run"
harness = false

[[example]]
name = "solve"

[[example]]
name = "3d"

[profile.bench]
debug = true 

[profile.release]
debug = true
