[package]
name = "crystacean"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "crystacean"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.1"
lattice_solver = { path = "../lattice_solver" }
